<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_account');
    } 

    /*
     * Listing of t_account
     */
    function index()
    {
        $data['t_account'] = $this->M_account->get_all_t_account();
        
        $data['_view'] = 'account/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_account
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_partner' => $this->input->post('id_partner'),
				'id_bank' => $this->input->post('id_bank'),
				'number' => $this->input->post('number'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $t_account_id = $this->M_account->add_t_account($params);
            redirect('account/index');
        }
        else
        {            
            $data['_view'] = 'account/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_account
     */
    function edit($id_account)
    {   
        // check if the t_account exists before trying to edit it
        $data['t_account'] = $this->M_account->get_t_account($id_account);
        
        if(isset($data['t_account']['id_account']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_partner' => $this->input->post('id_partner'),
					'id_bank' => $this->input->post('id_bank'),
					'number' => $this->input->post('number'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_account->update_t_account($id_account,$params);            
                redirect('account/index');
            }
            else
            {
                $data['_view'] = 'account/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_account you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_account
     */
    function remove($id_account)
    {
        $t_account = $this->M_account->get_t_account($id_account);

        // check if the t_account exists before trying to delete it
        if(isset($t_account['id_account']))
        {
            $this->M_account->delete_t_account($id_account);
            redirect('account/index');
        }
        else
            show_error('The t_account you are trying to delete does not exist.');
    }
    
}
