<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bank extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_bank');
    } 

    /*
     * Listing of m_bank
     */
    function index()
    {
        $data['m_bank'] = $this->M_bank->get_all_m_bank();
        
        $data['_view'] = 'bank/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_bank
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'bank_code' => $this->input->post('bank_code'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $m_bank_id = $this->M_bank->add_m_bank($params);
            redirect('bank/index');
        }
        else
        {            
            $data['_view'] = 'bank/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_bank
     */
    function edit($id_bank)
    {   
        // check if the m_bank exists before trying to edit it
        $data['m_bank'] = $this->M_bank->get_m_bank($id_bank);
        
        if(isset($data['m_bank']['id_bank']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'bank_code' => $this->input->post('bank_code'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_bank->update_m_bank($id_bank,$params);            
                redirect('bank/index');
            }
            else
            {
                $data['_view'] = 'bank/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_bank you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_bank
     */
    function remove($id_bank)
    {
        $m_bank = $this->M_bank->get_m_bank($id_bank);

        // check if the m_bank exists before trying to delete it
        if(isset($m_bank['id_bank']))
        {
            $this->M_bank->delete_m_bank($id_bank);
            redirect('bank/index');
        }
        else
            show_error('The m_bank you are trying to delete does not exist.');
    }
    
}
