<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Market_owner extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_market_owner');
    } 

    /*
     * Listing of t_market_owner
     */
    function index()
    {
        $data['t_market_owner'] = $this->M_market_owner->get_all_t_market_owner();
        
        $data['_view'] = 'market_owner/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_market_owner
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_partner' => $this->input->post('id_partner'),
				'id_market' => $this->input->post('id_market'),
				'name' => $this->input->post('name'),
				'url_name' => $this->input->post('url_name'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $t_market_owner_id = $this->M_market_owner->add_t_market_owner($params);
            redirect('market_owner/index');
        }
        else
        {            
            $data['_view'] = 'market_owner/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_market_owner
     */
    function edit($id_market_owner)
    {   
        // check if the t_market_owner exists before trying to edit it
        $data['t_market_owner'] = $this->M_market_owner->get_t_market_owner($id_market_owner);
        
        if(isset($data['t_market_owner']['id_market_owner']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_partner' => $this->input->post('id_partner'),
					'id_market' => $this->input->post('id_market'),
					'name' => $this->input->post('name'),
					'url_name' => $this->input->post('url_name'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_market_owner->update_t_market_owner($id_market_owner,$params);            
                redirect('market_owner/index');
            }
            else
            {
                $data['_view'] = 'market_owner/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_market_owner you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_market_owner
     */
    function remove($id_market_owner)
    {
        $t_market_owner = $this->M_market_owner->get_t_market_owner($id_market_owner);

        // check if the t_market_owner exists before trying to delete it
        if(isset($t_market_owner['id_market_owner']))
        {
            $this->M_market_owner->delete_t_market_owner($id_market_owner);
            redirect('market_owner/index');
        }
        else
            show_error('The t_market_owner you are trying to delete does not exist.');
    }
    
}
