<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Market extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_market');
    } 

    /*
     * Listing of m_market
     */
    function index()
    {
        $data['m_market'] = $this->M_market->get_all_m_market();
        
        $data['_view'] = 'market/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_market
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'url' => $this->input->post('url'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $m_market_id = $this->M_market->add_m_market($params);
            redirect('market/index');
        }
        else
        {            
            $data['_view'] = 'market/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_market
     */
    function edit($id_market)
    {   
        // check if the m_market exists before trying to edit it
        $data['m_market'] = $this->M_market->get_m_market($id_market);
        
        if(isset($data['m_market']['id_market']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'url' => $this->input->post('url'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_market->update_m_market($id_market,$params);            
                redirect('market/index');
            }
            else
            {
                $data['_view'] = 'market/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_market you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_market
     */
    function remove($id_market)
    {
        $m_market = $this->M_market->get_m_market($id_market);

        // check if the m_market exists before trying to delete it
        if(isset($m_market['id_market']))
        {
            $this->M_market->delete_m_market($id_market);
            redirect('market/index');
        }
        else
            show_error('The m_market you are trying to delete does not exist.');
    }
    
}
