<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Partner extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_partner');
    } 

    /*
     * Listing of t_partner
     */
    function index()
    {
        $data['t_partner'] = $this->M_partner->get_all_t_partner();
        
        $data['_view'] = 'partner/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_partner
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'email' => $this->input->post('email'),
				'phone' => $this->input->post('phone'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $t_partner_id = $this->M_partner->add_t_partner($params);
            redirect('partner/index');
        }
        else
        {            
            $data['_view'] = 'partner/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_partner
     */
    function edit($id_partner)
    {   
        // check if the t_partner exists before trying to edit it
        $data['t_partner'] = $this->M_partner->get_t_partner($id_partner);
        
        if(isset($data['t_partner']['id_partner']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'email' => $this->input->post('email'),
					'phone' => $this->input->post('phone'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_partner->update_t_partner($id_partner,$params);            
                redirect('partner/index');
            }
            else
            {
                $data['_view'] = 'partner/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_partner you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_partner
     */
    function remove($id_partner)
    {
        $t_partner = $this->M_partner->get_t_partner($id_partner);

        // check if the t_partner exists before trying to delete it
        if(isset($t_partner['id_partner']))
        {
            $this->M_partner->delete_t_partner($id_partner);
            redirect('partner/index');
        }
        else
            show_error('The t_partner you are trying to delete does not exist.');
    }
    
}
