<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Privilege extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_privilege');
    } 

    /*
     * Listing of m_privileges
     */
    function index()
    {
        $data['m_privileges'] = $this->M_privilege->get_all_m_privileges();
        
        $data['_view'] = 'privilege/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_privilege
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'const' => $this->input->post('const'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $m_privilege_id = $this->M_privilege->add_m_privilege($params);
            redirect('privilege/index');
        }
        else
        {            
            $data['_view'] = 'privilege/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_privilege
     */
    function edit($id_privileges)
    {   
        // check if the m_privilege exists before trying to edit it
        $data['m_privilege'] = $this->M_privilege->get_m_privilege($id_privileges);
        
        if(isset($data['m_privilege']['id_privileges']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'const' => $this->input->post('const'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_privilege->update_m_privilege($id_privileges,$params);            
                redirect('privilege/index');
            }
            else
            {
                $data['_view'] = 'privilege/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_privilege you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_privilege
     */
    function remove($id_privileges)
    {
        $m_privilege = $this->M_privilege->get_m_privilege($id_privileges);

        // check if the m_privilege exists before trying to delete it
        if(isset($m_privilege['id_privileges']))
        {
            $this->M_privilege->delete_m_privilege($id_privileges);
            redirect('privilege/index');
        }
        else
            show_error('The m_privilege you are trying to delete does not exist.');
    }
    
}
