<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transaction extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_transaction');
    } 

    /*
     * Listing of t_transaction
     */
    function index()
    {
        $data['t_transaction'] = $this->M_transaction->get_all_t_transaction();
        
        $data['_view'] = 'transaction/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_transaction
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_partner' => $this->input->post('id_partner'),
				'id_market_owner' => $this->input->post('id_market_owner'),
				'transaction_date' => $this->input->post('transaction_date'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $t_transaction_id = $this->M_transaction->add_t_transaction($params);
            redirect('transaction/index');
        }
        else
        {            
            $data['_view'] = 'transaction/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_transaction
     */
    function edit($id_m_transaction)
    {   
        // check if the t_transaction exists before trying to edit it
        $data['t_transaction'] = $this->M_transaction->get_t_transaction($id_m_transaction);
        
        if(isset($data['t_transaction']['id_m_transaction']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_partner' => $this->input->post('id_partner'),
					'id_market_owner' => $this->input->post('id_market_owner'),
					'transaction_date' => $this->input->post('transaction_date'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_transaction->update_t_transaction($id_m_transaction,$params);            
                redirect('transaction/index');
            }
            else
            {
                $data['_view'] = 'transaction/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_transaction you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_transaction
     */
    function remove($id_m_transaction)
    {
        $t_transaction = $this->M_transaction->get_t_transaction($id_m_transaction);

        // check if the t_transaction exists before trying to delete it
        if(isset($t_transaction['id_m_transaction']))
        {
            $this->M_transaction->delete_t_transaction($id_m_transaction);
            redirect('transaction/index');
        }
        else
            show_error('The t_transaction you are trying to delete does not exist.');
    }
    
}
