<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transaction_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_transaction_detail');
    } 

    /*
     * Listing of t_transaction_detail
     */
    function index()
    {
        $data['t_transaction_detail'] = $this->M_transaction_detail->get_all_t_transaction_detail();
        
        $data['_view'] = 'transaction_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_transaction_detail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_m_transaction' => $this->input->post('id_m_transaction'),
				'id_type' => $this->input->post('id_type'),
				'item_name' => $this->input->post('item_name'),
				'item_count' => $this->input->post('item_count'),
				'item_price_buy' => $this->input->post('item_price_buy'),
				'item_price_sell' => $this->input->post('item_price_sell'),
				'from_name' => $this->input->post('from_name'),
				'from_address' => $this->input->post('from_address'),
				'ongkir' => $this->input->post('ongkir'),
				'request_name' => $this->input->post('request_name'),
				'request_address' => $this->input->post('request_address'),
				'request_date' => $this->input->post('request_date'),
				'resi' => $this->input->post('resi'),
				'is_sent' => $this->input->post('is_sent'),
				'sent_date' => $this->input->post('sent_date'),
				'is_arrived' => $this->input->post('is_arrived'),
				'arrived_date' => $this->input->post('arrived_date'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $t_transaction_detail_id = $this->M_transaction_detail->add_t_transaction_detail($params);
            redirect('transaction_detail/index');
        }
        else
        {            
            $data['_view'] = 'transaction_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_transaction_detail
     */
    function edit($id_t_transaction)
    {   
        // check if the t_transaction_detail exists before trying to edit it
        $data['t_transaction_detail'] = $this->M_transaction_detail->get_t_transaction_detail($id_t_transaction);
        
        if(isset($data['t_transaction_detail']['id_t_transaction']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_m_transaction' => $this->input->post('id_m_transaction'),
					'id_type' => $this->input->post('id_type'),
					'item_name' => $this->input->post('item_name'),
					'item_count' => $this->input->post('item_count'),
					'item_price_buy' => $this->input->post('item_price_buy'),
					'item_price_sell' => $this->input->post('item_price_sell'),
					'from_name' => $this->input->post('from_name'),
					'from_address' => $this->input->post('from_address'),
					'ongkir' => $this->input->post('ongkir'),
					'request_name' => $this->input->post('request_name'),
					'request_address' => $this->input->post('request_address'),
					'request_date' => $this->input->post('request_date'),
					'resi' => $this->input->post('resi'),
					'is_sent' => $this->input->post('is_sent'),
					'sent_date' => $this->input->post('sent_date'),
					'is_arrived' => $this->input->post('is_arrived'),
					'arrived_date' => $this->input->post('arrived_date'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_transaction_detail->update_t_transaction_detail($id_t_transaction,$params);            
                redirect('transaction_detail/index');
            }
            else
            {
                $data['_view'] = 'transaction_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_transaction_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_transaction_detail
     */
    function remove($id_t_transaction)
    {
        $t_transaction_detail = $this->M_transaction_detail->get_t_transaction_detail($id_t_transaction);

        // check if the t_transaction_detail exists before trying to delete it
        if(isset($t_transaction_detail['id_t_transaction']))
        {
            $this->M_transaction_detail->delete_t_transaction_detail($id_t_transaction);
            redirect('transaction_detail/index');
        }
        else
            show_error('The t_transaction_detail you are trying to delete does not exist.');
    }
    
}
