<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transfer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_transfer');
    } 

    /*
     * Listing of t_transfer
     */
    function index()
    {
        $data['t_transfer'] = $this->M_transfer->get_all_t_transfer();
        
        $data['_view'] = 'transfer/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_transfer
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_account' => $this->input->post('id_account'),
				'id_transaction_detail' => $this->input->post('id_transaction_detail'),
				'is_va' => $this->input->post('is_va'),
				'va_number' => $this->input->post('va_number'),
				'amount' => $this->input->post('amount'),
				'is_transfered' => $this->input->post('is_transfered'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
            );
            
            $t_transfer_id = $this->M_transfer->add_t_transfer($params);
            redirect('transfer/index');
        }
        else
        {            
            $data['_view'] = 'transfer/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_transfer
     */
    function edit($id_transfer)
    {   
        // check if the t_transfer exists before trying to edit it
        $data['t_transfer'] = $this->M_transfer->get_t_transfer($id_transfer);
        
        if(isset($data['t_transfer']['id_transfer']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_account' => $this->input->post('id_account'),
					'id_transaction_detail' => $this->input->post('id_transaction_detail'),
					'is_va' => $this->input->post('is_va'),
					'va_number' => $this->input->post('va_number'),
					'amount' => $this->input->post('amount'),
					'is_transfered' => $this->input->post('is_transfered'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
                );

                $this->M_transfer->update_t_transfer($id_transfer,$params);            
                redirect('transfer/index');
            }
            else
            {
                $data['_view'] = 'transfer/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_transfer you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_transfer
     */
    function remove($id_transfer)
    {
        $t_transfer = $this->M_transfer->get_t_transfer($id_transfer);

        // check if the t_transfer exists before trying to delete it
        if(isset($t_transfer['id_transfer']))
        {
            $this->M_transfer->delete_t_transfer($id_transfer);
            redirect('transfer/index');
        }
        else
            show_error('The t_transfer you are trying to delete does not exist.');
    }
    
}
