<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_user');
    }

    /*
     * Listing of t_user
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('t_user/index?');
        $config['total_rows'] = $this->M_user->get_all_t_user_count();
        $this->pagination->initialize($config);

        $data['t_user'] = $this->M_user->get_all_t_user($params);

        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_user
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'password' => $this->input->post('password'),
				'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
				'id_privileges' => $this->input->post('id_privileges'),
				'created_by' => $this->input->post('created_by'),
				'modified_by' => $this->input->post('modified_by'),
				'created_date' => $this->input->post('created_date'),
				'modified_date' => $this->input->post('modified_date'),
				'last_login' => $this->input->post('last_login'),
            );

            $t_user_id = $this->M_user->add_t_user($params);
            redirect('user/index');
        }
        else
        {
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a t_user
     */
    function edit($id_user)
    {
        // check if the t_user exists before trying to edit it
        $data['t_user'] = $this->M_user->get_t_user($id_user);

        if(isset($data['t_user']['id_user']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
					'id_privileges' => $this->input->post('id_privileges'),
					'created_by' => $this->input->post('created_by'),
					'modified_by' => $this->input->post('modified_by'),
					'created_date' => $this->input->post('created_date'),
					'modified_date' => $this->input->post('modified_date'),
					'last_login' => $this->input->post('last_login'),
                );

                $this->M_user->update_t_user($id_user,$params);
                redirect('user/index');
            }
            else
            {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_user you are trying to edit does not exist.');
    }

    /*
     * Deleting t_user
     */
    function remove($id_user)
    {
        $t_user = $this->M_user->get_t_user($id_user);

        // check if the t_user exists before trying to delete it
        if(isset($t_user['id_user']))
        {
            $this->M_user->delete_t_user($id_user);
            redirect('user/index');
        }
        else
            show_error('The t_user you are trying to delete does not exist.');
    }

}
