<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_account extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_account by id_account
     */
    function get_t_account($id_account)
    {
        return $this->db->get_where('t_account',array('id_account'=>$id_account))->row_array();
    }
        
    /*
     * Get all t_account
     */
    function get_all_t_account()
    {
        $this->db->order_by('id_account', 'desc');
        return $this->db->get('t_account')->result_array();
    }
        
    /*
     * function to add new t_account
     */
    function add_t_account($params)
    {
        $this->db->insert('t_account',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_account
     */
    function update_t_account($id_account,$params)
    {
        $this->db->where('id_account',$id_account);
        return $this->db->update('t_account',$params);
    }
    
    /*
     * function to delete t_account
     */
    function delete_t_account($id_account)
    {
        return $this->db->delete('t_account',array('id_account'=>$id_account));
    }
}
