<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_bank extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_bank by id_bank
     */
    function get_m_bank($id_bank)
    {
        return $this->db->get_where('m_bank',array('id_bank'=>$id_bank))->row_array();
    }
        
    /*
     * Get all m_bank
     */
    function get_all_m_bank()
    {
        $this->db->order_by('id_bank', 'desc');
        return $this->db->get('m_bank')->result_array();
    }
        
    /*
     * function to add new m_bank
     */
    function add_m_bank($params)
    {
        $this->db->insert('m_bank',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_bank
     */
    function update_m_bank($id_bank,$params)
    {
        $this->db->where('id_bank',$id_bank);
        return $this->db->update('m_bank',$params);
    }
    
    /*
     * function to delete m_bank
     */
    function delete_m_bank($id_bank)
    {
        return $this->db->delete('m_bank',array('id_bank'=>$id_bank));
    }
}
