<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_market extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_market by id_market
     */
    function get_m_market($id_market)
    {
        return $this->db->get_where('m_market',array('id_market'=>$id_market))->row_array();
    }
        
    /*
     * Get all m_market
     */
    function get_all_m_market()
    {
        $this->db->order_by('id_market', 'desc');
        return $this->db->get('m_market')->result_array();
    }
        
    /*
     * function to add new m_market
     */
    function add_m_market($params)
    {
        $this->db->insert('m_market',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_market
     */
    function update_m_market($id_market,$params)
    {
        $this->db->where('id_market',$id_market);
        return $this->db->update('m_market',$params);
    }
    
    /*
     * function to delete m_market
     */
    function delete_m_market($id_market)
    {
        return $this->db->delete('m_market',array('id_market'=>$id_market));
    }
}
