<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_market_owner extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_market_owner by id_market_owner
     */
    function get_t_market_owner($id_market_owner)
    {
        return $this->db->get_where('t_market_owner',array('id_market_owner'=>$id_market_owner))->row_array();
    }
        
    /*
     * Get all t_market_owner
     */
    function get_all_t_market_owner()
    {
        $this->db->order_by('id_market_owner', 'desc');
        return $this->db->get('t_market_owner')->result_array();
    }
        
    /*
     * function to add new t_market_owner
     */
    function add_t_market_owner($params)
    {
        $this->db->insert('t_market_owner',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_market_owner
     */
    function update_t_market_owner($id_market_owner,$params)
    {
        $this->db->where('id_market_owner',$id_market_owner);
        return $this->db->update('t_market_owner',$params);
    }
    
    /*
     * function to delete t_market_owner
     */
    function delete_t_market_owner($id_market_owner)
    {
        return $this->db->delete('t_market_owner',array('id_market_owner'=>$id_market_owner));
    }
}
