<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_partner extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_partner by id_partner
     */
    function get_t_partner($id_partner)
    {
        return $this->db->get_where('t_partner',array('id_partner'=>$id_partner))->row_array();
    }
        
    /*
     * Get all t_partner
     */
    function get_all_t_partner()
    {
        $this->db->order_by('id_partner', 'desc');
        return $this->db->get('t_partner')->result_array();
    }
        
    /*
     * function to add new t_partner
     */
    function add_t_partner($params)
    {
        $this->db->insert('t_partner',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_partner
     */
    function update_t_partner($id_partner,$params)
    {
        $this->db->where('id_partner',$id_partner);
        return $this->db->update('t_partner',$params);
    }
    
    /*
     * function to delete t_partner
     */
    function delete_t_partner($id_partner)
    {
        return $this->db->delete('t_partner',array('id_partner'=>$id_partner));
    }
}
