<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_privilege extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_privilege by id_privileges
     */
    function get_m_privilege($id_privileges)
    {
        return $this->db->get_where('m_privileges',array('id_privileges'=>$id_privileges))->row_array();
    }
        
    /*
     * Get all m_privileges
     */
    function get_all_m_privileges()
    {
        $this->db->order_by('id_privileges', 'desc');
        return $this->db->get('m_privileges')->result_array();
    }
        
    /*
     * function to add new m_privilege
     */
    function add_m_privilege($params)
    {
        $this->db->insert('m_privileges',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_privilege
     */
    function update_m_privilege($id_privileges,$params)
    {
        $this->db->where('id_privileges',$id_privileges);
        return $this->db->update('m_privileges',$params);
    }
    
    /*
     * function to delete m_privilege
     */
    function delete_m_privilege($id_privileges)
    {
        return $this->db->delete('m_privileges',array('id_privileges'=>$id_privileges));
    }
}
