<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_transaction extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_transaction by id_m_transaction
     */
    function get_t_transaction($id_m_transaction)
    {
        return $this->db->get_where('t_transaction',array('id_m_transaction'=>$id_m_transaction))->row_array();
    }
        
    /*
     * Get all t_transaction
     */
    function get_all_t_transaction()
    {
        $this->db->order_by('id_m_transaction', 'desc');
        return $this->db->get('t_transaction')->result_array();
    }
        
    /*
     * function to add new t_transaction
     */
    function add_t_transaction($params)
    {
        $this->db->insert('t_transaction',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_transaction
     */
    function update_t_transaction($id_m_transaction,$params)
    {
        $this->db->where('id_m_transaction',$id_m_transaction);
        return $this->db->update('t_transaction',$params);
    }
    
    /*
     * function to delete t_transaction
     */
    function delete_t_transaction($id_m_transaction)
    {
        return $this->db->delete('t_transaction',array('id_m_transaction'=>$id_m_transaction));
    }
}
