<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_transfer extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_transfer by id_transfer
     */
    function get_t_transfer($id_transfer)
    {
        return $this->db->get_where('t_transfer',array('id_transfer'=>$id_transfer))->row_array();
    }
        
    /*
     * Get all t_transfer
     */
    function get_all_t_transfer()
    {
        $this->db->order_by('id_transfer', 'desc');
        return $this->db->get('t_transfer')->result_array();
    }
        
    /*
     * function to add new t_transfer
     */
    function add_t_transfer($params)
    {
        $this->db->insert('t_transfer',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_transfer
     */
    function update_t_transfer($id_transfer,$params)
    {
        $this->db->where('id_transfer',$id_transfer);
        return $this->db->update('t_transfer',$params);
    }
    
    /*
     * function to delete t_transfer
     */
    function delete_t_transfer($id_transfer)
    {
        return $this->db->delete('t_transfer',array('id_transfer'=>$id_transfer));
    }
}
