<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_transaction_detail extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_transaction_detail by id_t_transaction
     */
    function get_t_transaction_detail($id_t_transaction)
    {
        return $this->db->get_where('t_transaction_detail',array('id_t_transaction'=>$id_t_transaction))->row_array();
    }
        
    /*
     * Get all t_transaction_detail
     */
    function get_all_t_transaction_detail()
    {
        $this->db->order_by('id_t_transaction', 'desc');
        return $this->db->get('t_transaction_detail')->result_array();
    }
        
    /*
     * function to add new t_transaction_detail
     */
    function add_t_transaction_detail($params)
    {
        $this->db->insert('t_transaction_detail',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_transaction_detail
     */
    function update_t_transaction_detail($id_t_transaction,$params)
    {
        $this->db->where('id_t_transaction',$id_t_transaction);
        return $this->db->update('t_transaction_detail',$params);
    }
    
    /*
     * function to delete t_transaction_detail
     */
    function delete_t_transaction_detail($id_t_transaction)
    {
        return $this->db->delete('t_transaction_detail',array('id_t_transaction'=>$id_t_transaction));
    }
}
