<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_user extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_user by id_user
     */
    function get_t_user($id_user)
    {
        return $this->db->get_where('t_user',array('id_user'=>$id_user))->row_array();
    }
    
    /*
     * Get all t_user count
     */
    function get_all_t_user_count()
    {
        $this->db->from('t_user');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all t_user
     */
    function get_all_t_user($params = array())
    {
        $this->db->order_by('id_user', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('t_user')->result_array();
    }
        
    /*
     * function to add new t_user
     */
    function add_t_user($params)
    {
        $this->db->insert('t_user',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_user
     */
    function update_t_user($id_user,$params)
    {
        $this->db->where('id_user',$id_user);
        return $this->db->update('t_user',$params);
    }
    
    /*
     * function to delete t_user
     */
    function delete_t_user($id_user)
    {
        return $this->db->delete('t_user',array('id_user'=>$id_user));
    }
}
